name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm pack

    - name: Release
      uses: google-github-actions/release-please-action@v3
      id: create_release
      with:
        release-type: node
        package-name: testcli

    - name: Upload binaries to release
      if: steps.create_release.outputs.release_created
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./samoldham-testcli-${{steps.create_release.outputs.major}}.${{steps.create_release.outputs.minor}}.${{steps.create_release.outputs.patch}}.tgz
        asset_name: package.tar.gz
        tag: ${{ steps.create_release.outputs.tag_name }}

    - name: Set up node
      if: steps.create_release.outputs.release_created
      uses: actions/setup-node@v3
      with: 
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'

      if: steps.create_release.outputs.release_created
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}
